name: Build LoadRunner Cloud Test
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      lrc_server:
        description: LRC URL
        required: true
        default: 'https://loadrunner-cloud.saas.microfocus.com'
      lrc_tenant:
        description: Tenant ID
        required: true
      lrc_project:
        description: Project ID
        required: true
        default: '1'
      lrc_test_id:
        description: Test ID
        required: true
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Run Load Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test in LoadRunner Cloud
        id: lrc_run_test
        env:
          LRC_CLIENT_ID: '${{secrets.LRC_CLIENT_ID}}'
          LRC_CLIENT_SECRET: '${{secrets.LRC_CLIENT_SECRET}}'
        with:
          lrc_server: >-
            ${{ github.event.inputs.lrc_server ||
            'https://loadrunner-cloud.saas.microfocus.com' }}
          lrc_tenant: '${{ github.event.inputs.lrc_tenant || secrets.LRC_TENANT_ID }}'
          lrc_project: '${{ github.event.inputs.lrc_project || secrets.LRC_PROJECT_ID }}'
          lrc_test_id: '${{ github.event.inputs.lrc_test_id || secrets.LRC_TEST_ID }}'
        uses: ./
      - name: Print test run ID
        run: 'echo "LRC Run ID is ${{ steps.lrc_run_test.outputs.lrc_run_id }}"'

