name: Trigger LoadRunner Cloud Test
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  trigger-lrc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get LoadRunner Cloud Token
        id: get-token
        run: >
          TOKEN_RESPONSE=$(curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "client_id": "${{ secrets.LRC_CLIENT_ID }}",
              "client_secret": "${{ secrets.LRC_SECRET_KEY }}"
            }' \
            https://loadrunner-cloud.saas.microfocus.com/v1/auth/login)
          echo "token=$(echo $TOKEN_RESPONSE | jq -r '.token')" >>
          $GITHUB_OUTPUT
      - name: Trigger LoadRunner Cloud Test
        env:
          LRC_PROJECT_ID: '${{ secrets.LRC_PROJECT_ID }}'
          LRC_TEST_ID: '${{ secrets.LRC_TEST_ID }}'
        run: >
          curl -X POST \

          -H "Content-Type: application/json" \

          -H "Authorization: Bearer ${{ steps.get-token.outputs.token }}" \

          -d '{
            "projectId": "'$LRC_PROJECT_ID'",
            "testId": "'$LRC_TEST_ID'",
            "executionSettings": {
              "duration": 30,
              "vusers": 10,
              "loadProfile": "default"
            }
          }' \

          "https://loadrunner-cloud.saas.microfocus.com/v1/projects/$LRC_PROJECT_ID/tests/$LRC_TEST_ID/runs"
