name: Trigger LoadRunner Cloud Test
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  trigger-lrc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Trigger LoadRunner Cloud Test
        env:
          LRC_CLIENT_ID: '${{ secrets.LRC_CLIENT_ID }}'
          LRC_SECRET_KEY: '${{ secrets.LRC_SECRET_KEY }}'
          LRC_PROJECT_ID: '${{ secrets.LRC_PROJECT_ID }}'
          LRC_TEST_ID: '${{ secrets.LRC_TEST_ID }}'
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
                "clientId": "'$LRC_CLIENT_ID'",
                "clientSecret": "'$LRC_SECRET_KEY'",
                "testId": "'$LRC_TEST_ID'",
                "executionSettings": {
                  "duration": 30,
                  "loadProfile": "default"
                }
              }' \
          https://loadrunner-cloud.saas.microfocus.com/loadTests/123/scripts/?TENANTID=688577294&projectId=1
