name: Trigger LoadRunner Cloud Test
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  trigger-lrc-test:
    runs-on: self-hosted
    name: Start a load test
    steps:
      - name: Run test in LoadRunner Cloud
        uses: actions/Perftest1@v1
        id: lrc_run_test
        env:
          LRC_CLIENT_ID: '${{ secrets.LRC_CLIENT_ID }}'
          LRC_SECRET_KEY: '${{ secrets.LRC_SECRET_KEY }}'
          LRC_PROJECT_ID: '${{ secrets.LRC_PROJECT_ID }}'
          LRC_TEST_ID: '${{ secrets.LRC_TEST_ID }}'
        with:
          lrc_server: 'https://loadrunner-cloud.saas.microfocus.com'
          lrc_tenant: '688577294'
          lrc_project: '1'
          lrc_test_id: '123'
